// ------------------------------------------------------------------
// QUESTION BANK — organized into chapters per subject.
//
// Each subject has 3 chapters of real, increasing difficulty:
// Beginner -> Intermediate -> Advanced. This is written content, not
// AI-generated, so "harder" here means genuinely harder questions —
// not just more of them. Completing a chapter unlocks the next one
// (see chapterProgress logic in app.js).
//
// In a later version, replace this with a real AI backend that can
// generate infinite tiered questions instead of a fixed set — see the
// README for how that fits in.
// ------------------------------------------------------------------

const SUBJECTS = [
  { id: "math", name: "Math", icon: "🧮" },
  { id: "science", name: "Science", icon: "🔬" },
  { id: "history", name: "History", icon: "📜" },
  { id: "geography", name: "Geography", icon: "🌍" },
  { id: "english", name: "English", icon: "📖" },
  { id: "computer-science", name: "Computer Science", icon: "💻" },
  { id: "economics", name: "Economics", icon: "💰" }
];

const CHAPTER_NAMES = ["Beginner", "Intermediate", "Advanced"];

// QUESTION_BANK[subjectId] = [ [chapter0 questions], [chapter1], [chapter2] ]
const QUESTION_BANK = {
  math: [
    [
      { q: "What is 7 × 8?", options: ["54", "56", "64", "48"], correct: 1,
        explanation: "7 × 8 means adding 7 eight times: 7+7+7+7+7+7+7+7 = 56." },
      { q: "What is the square root of 144?", options: ["11", "12", "13", "14"], correct: 1,
        explanation: "12 × 12 = 144, so the square root of 144 is 12." },
      { q: "What is 15% of 200?", options: ["20", "25", "30", "35"], correct: 2,
        explanation: "15% means 15 out of 100. Multiply: 200 × 0.15 = 30." },
      { q: "What is 9² (9 squared)?", options: ["18", "72", "81", "99"], correct: 2,
        explanation: "A number squared means multiplying it by itself: 9 × 9 = 81." },
      { q: "What is the area of a rectangle 4cm by 9cm?", options: ["13 cm²", "26 cm²", "36 cm²", "40 cm²"], correct: 2,
        explanation: "Area of a rectangle = length × width = 4 × 9 = 36 cm²." },
      { q: "What is 12 + 15?", options: ["25", "26", "27", "28"], correct: 2,
        explanation: "12 + 15 = 27, adding the two numbers directly." },
      { q: "What is 100 ÷ 4?", options: ["20", "25", "30", "40"], correct: 1,
        explanation: "100 divided by 4 equals 25, since 4 × 25 = 100." },
      { q: "What is 3 × 3 × 3?", options: ["9", "18", "27", "36"], correct: 2,
        explanation: "3 × 3 = 9, then 9 × 3 = 27." },
      { q: "Which of these numbers is a prime number?", options: ["4", "6", "7", "9"], correct: 2,
        explanation: "A prime number has exactly two factors, 1 and itself. 7 is only divisible by 1 and 7." },
      { q: "What is 1/2 + 1/4?", options: ["1/6", "2/6", "3/4", "1/8"], correct: 2,
        explanation: "Convert 1/2 to 2/4, then 2/4 + 1/4 = 3/4." }
    ],
    [
      { q: "Solve for x: 2x + 5 = 17", options: ["5", "6", "7", "8"], correct: 1,
        explanation: "Subtract 5 from both sides: 2x = 12. Then divide both sides by 2: x = 6." },
      { q: "What is the perimeter of a square with side length 6cm?", options: ["12", "18", "24", "36"], correct: 2,
        explanation: "Perimeter of a square = 4 × side = 4 × 6 = 24 cm." },
      { q: "Simplify: 3(x + 4)", options: ["3x + 4", "3x + 12", "x + 12", "3x + 7"], correct: 1,
        explanation: "Distribute the 3 across (x + 4): 3 × x = 3x, and 3 × 4 = 12, giving 3x + 12." },
      { q: "What is the value of 5! (5 factorial)?", options: ["20", "60", "120", "150"], correct: 2,
        explanation: "5! means 5 × 4 × 3 × 2 × 1 = 120." },
      { q: "If a triangle has angles 50° and 60°, what is the third angle?", options: ["60°", "70°", "80°", "90°"], correct: 1,
        explanation: "The angles in a triangle always sum to 180°. 180 − 50 − 60 = 70°." },
      { q: "What is 20% of 150?", options: ["20", "25", "30", "35"], correct: 2,
        explanation: "20% of 150 = 150 × 0.20 = 30." },
      { q: "Solve for y: y/3 = 9", options: ["3", "12", "27", "36"], correct: 2,
        explanation: "Multiply both sides by 3: y = 9 × 3 = 27." },
      { q: "What is the circumference of a circle with radius 5? (use π ≈ 3.14)", options: ["15.7", "31.4", "62.8", "78.5"], correct: 1,
        explanation: "Circumference = 2πr = 2 × 3.14 × 5 = 31.4." },
      { q: "Simplify: 4x − 2x + 6", options: ["2x + 6", "6x + 6", "2x − 6", "4x + 6"], correct: 0,
        explanation: "Combine like terms: 4x − 2x = 2x, so the result is 2x + 6." },
      { q: "What is the median of the numbers 3, 7, 9, 12, 15?", options: ["7", "9", "10", "12"], correct: 1,
        explanation: "The median is the middle value when numbers are ordered. Here, 9 sits exactly in the middle of the 5 values." }
    ],
    [
      { q: "Solve: x² = 49. What are the possible values of x?", options: ["7 only", "-7 only", "7 and -7", "49"], correct: 2,
        explanation: "Both 7 × 7 = 49 and (-7) × (-7) = 49, so x can be either 7 or -7." },
      { q: "What is the slope of the line through points (2,3) and (4,7)?", options: ["1", "2", "3", "4"], correct: 1,
        explanation: "Slope = (y₂ − y₁) / (x₂ − x₁) = (7 − 3) / (4 − 2) = 4 / 2 = 2." },
      { q: "Simplify: (2x²)(3x³)", options: ["5x⁵", "6x⁵", "6x⁶", "5x⁶"], correct: 1,
        explanation: "Multiply the coefficients (2 × 3 = 6) and add the exponents (2 + 3 = 5), giving 6x⁵." },
      { q: "What is the sum of the interior angles of a hexagon?", options: ["360°", "540°", "720°", "900°"], correct: 2,
        explanation: "Sum of interior angles = (n − 2) × 180°. For a hexagon, n = 6: (6 − 2) × 180° = 720°." },
      { q: "Solve for x: log₂(x) = 5", options: ["10", "16", "25", "32"], correct: 3,
        explanation: "log₂(x) = 5 means 2⁵ = x, and 2⁵ = 32." },
      { q: "What is the derivative of x² with respect to x?", options: ["x", "2x", "x²", "2"], correct: 1,
        explanation: "Using the power rule, the derivative of xⁿ is n·x^(n-1); for x², that's 2x¹ = 2x." },
      { q: "What is the value of sin(90°)?", options: ["0", "0.5", "1", "Undefined"], correct: 2,
        explanation: "sin(90°) equals 1, the maximum value of the sine function." },
      { q: "Solve the system: x + y = 10, x − y = 2. What is x?", options: ["4", "5", "6", "8"], correct: 2,
        explanation: "Adding both equations: 2x = 12, so x = 6 (and y = 4)." },
      { q: "What is the probability of rolling a sum of 7 with two six-sided dice?", options: ["1/6", "1/12", "5/36", "1/36"], correct: 0,
        explanation: "6 combinations sum to 7 (1+6, 2+5, 3+4, 4+3, 5+2, 6+1) out of 36 total outcomes: 6/36 = 1/6." },
      { q: "What is the quadratic formula used to solve ax² + bx + c = 0?", options: ["x = (−b ± √(b²−4ac)) / 2a", "x = −b / 2a", "x = b² − 4ac", "x = (−b + c) / a"], correct: 0,
        explanation: "The quadratic formula, x = (−b ± √(b²−4ac)) / 2a, gives the solutions to any quadratic equation in standard form." }
    ]
  ],
  science: [
    [
      { q: "What planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], correct: 1,
        explanation: "Mars appears reddish because its surface is covered in iron oxide, better known as rust." },
      { q: "What gas do plants absorb from the atmosphere for photosynthesis?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correct: 2,
        explanation: "Plants take in carbon dioxide through tiny pores called stomata, using it with sunlight and water to produce glucose and oxygen." },
      { q: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], correct: 2,
        explanation: "'Au' comes from 'aurum,' the Latin word for gold." },
      { q: "How many bones are in the adult human body?", options: ["186", "206", "226", "246"], correct: 1,
        explanation: "Babies are born with around 300 bones, many of which fuse together as they grow, leaving adults with 206." },
      { q: "What force pulls objects toward the Earth?", options: ["Magnetism", "Friction", "Gravity", "Tension"], correct: 2,
        explanation: "Gravity is the force of attraction between objects with mass — Earth's gravity pulls objects toward its center." },
      { q: "What is the closest star to Earth?", options: ["Proxima Centauri", "The Sun", "Sirius", "Alpha Centauri"], correct: 1,
        explanation: "The Sun is by far the closest star to Earth, about 150 million km away." },
      { q: "Which sense organ is used for hearing?", options: ["Eyes", "Ears", "Nose", "Skin"], correct: 1,
        explanation: "Ears detect sound waves and convert them into signals the brain interprets as hearing." },
      { q: "What do we call animals that only eat plants?", options: ["Carnivores", "Herbivores", "Omnivores", "Insectivores"], correct: 1,
        explanation: "Herbivores are animals whose diet consists mainly or entirely of plant material." },
      { q: "What is the freezing point of water in Celsius?", options: ["-10°", "0°", "10°", "32°"], correct: 1,
        explanation: "Water freezes at 0°C (32°F) at standard atmospheric pressure." },
      { q: "Which gas do humans need to breathe in to survive?", options: ["Carbon dioxide", "Nitrogen", "Oxygen", "Helium"], correct: 2,
        explanation: "Humans need oxygen for cellular respiration, which produces the energy our bodies use." }
    ],
    [
      { q: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi body"], correct: 2,
        explanation: "Mitochondria convert nutrients into ATP, the energy cells run on — hence the nickname." },
      { q: "What state of matter has a fixed volume but no fixed shape?", options: ["Solid", "Liquid", "Gas", "Plasma"], correct: 1,
        explanation: "Liquids keep a constant volume but take the shape of their container, unlike gases, which expand to fill any space." },
      { q: "What is the boiling point of water at sea level, in Celsius?", options: ["90°", "100°", "110°", "120°"], correct: 1,
        explanation: "At standard atmospheric pressure, water boils at 100°C (212°F)." },
      { q: "Which organ pumps blood through the body?", options: ["Liver", "Lungs", "Heart", "Kidney"], correct: 2,
        explanation: "The heart is a muscular organ that pumps blood through the circulatory system." },
      { q: "What type of energy is stored in a stretched rubber band?", options: ["Kinetic", "Potential", "Thermal", "Chemical"], correct: 1,
        explanation: "Stretched or compressed objects store elastic potential energy, released when they return to their original shape." },
      { q: "What is the main function of red blood cells?", options: ["Fight infection", "Carry oxygen", "Clot blood", "Digest food"], correct: 1,
        explanation: "Red blood cells contain hemoglobin, which binds to oxygen and carries it throughout the body." },
      { q: "What is the chemical formula for water?", options: ["CO2", "H2O", "O2", "NaCl"], correct: 1,
        explanation: "Water is made of two hydrogen atoms and one oxygen atom, giving the formula H2O." },
      { q: "What type of rock is formed from cooled lava or magma?", options: ["Sedimentary", "Metamorphic", "Igneous", "Fossil"], correct: 2,
        explanation: "Igneous rocks form when molten rock (lava or magma) cools and solidifies." },
      { q: "Which planet is known for its prominent rings?", options: ["Mars", "Saturn", "Mercury", "Venus"], correct: 1,
        explanation: "Saturn is famous for its extensive, visible ring system made mostly of ice and rock particles." },
      { q: "What is the process by which water changes from liquid to gas called?", options: ["Condensation", "Evaporation", "Precipitation", "Sublimation"], correct: 1,
        explanation: "Evaporation is when liquid water absorbs enough heat energy to turn into water vapor (gas)." }
    ],
    [
      { q: "What is Newton's second law of motion?", options: ["F = ma", "E = mc²", "P = IV", "V = IR"], correct: 0,
        explanation: "Newton's second law states that force equals mass times acceleration (F = ma)." },
      { q: "What particle has a negative charge?", options: ["Proton", "Neutron", "Electron", "Photon"], correct: 2,
        explanation: "Electrons carry a negative electric charge and orbit the nucleus of an atom." },
      { q: "What process do cells use to divide and produce identical copies?", options: ["Meiosis", "Mitosis", "Osmosis", "Diffusion"], correct: 1,
        explanation: "Mitosis is the process where a cell divides to produce two genetically identical daughter cells." },
      { q: "What is the pH of a neutral solution?", options: ["0", "7", "10", "14"], correct: 1,
        explanation: "pH 7 is neutral; below 7 is acidic, and above 7 is basic (alkaline)." },
      { q: "What law states that energy cannot be created or destroyed, only transformed?", options: ["Law of Gravity", "Law of Conservation of Energy", "Newton's Third Law", "Law of Inertia"], correct: 1,
        explanation: "The Law of Conservation of Energy states energy can change form, but the total amount stays constant in an isolated system." },
      { q: "What is the speed of light in a vacuum (approximately)?", options: ["3×10⁵ km/s", "3×10⁸ m/s", "3×10³ m/s", "3×10⁸ km/s"], correct: 1,
        explanation: "Light travels at approximately 299,792,458 meters per second in a vacuum, commonly rounded to 3×10⁸ m/s." },
      { q: "What is the atomic number of an element determined by?", options: ["Number of neutrons", "Number of protons", "Number of electrons only", "Atomic mass"], correct: 1,
        explanation: "The atomic number is defined as the number of protons in an atom's nucleus, which determines the element." },
      { q: "What type of bond involves atoms sharing electrons?", options: ["Ionic bond", "Covalent bond", "Metallic bond", "Hydrogen bond"], correct: 1,
        explanation: "Covalent bonds form when atoms share pairs of electrons, common in molecules like water and methane." },
      { q: "What does Charles's Law describe?", options: ["The relationship between pressure and volume", "The relationship between a gas's volume and temperature", "The speed of chemical reactions", "The behavior of light"], correct: 1,
        explanation: "Charles's Law states that at constant pressure, a gas's volume is directly proportional to its temperature." },
      { q: "Which part of the brain is responsible for balance and coordination?", options: ["Cerebrum", "Cerebellum", "Medulla oblongata", "Hypothalamus"], correct: 1,
        explanation: "The cerebellum coordinates voluntary movements, posture, and balance." }
    ]
  ],
  history: [
    [
      { q: "In what year did World War II end?", options: ["1943", "1945", "1947", "1950"], correct: 1,
        explanation: "Germany surrendered in May 1945, and Japan surrendered in September 1945, ending the war." },
      { q: "Who was the first President of the United States?", options: ["Thomas Jefferson", "John Adams", "George Washington", "Benjamin Franklin"], correct: 2,
        explanation: "George Washington served as the first U.S. President from 1789 to 1797, setting many precedents still followed today." },
      { q: "The ancient pyramids of Giza are located in which country?", options: ["Mexico", "Egypt", "Peru", "Sudan"], correct: 1,
        explanation: "The Giza pyramid complex was built as royal tombs for Egyptian pharaohs around 2500 BCE." },
      { q: "Which empire built the Colosseum?", options: ["Greek", "Roman", "Ottoman", "Persian"], correct: 1,
        explanation: "The Colosseum was completed around 80 CE under the Roman Empire and used for gladiator contests and public spectacles." },
      { q: "What wall divided a European city during the Cold War?", options: ["Vienna Wall", "Berlin Wall", "Warsaw Wall", "Prague Wall"], correct: 1,
        explanation: "The Berlin Wall divided East and West Berlin from 1961 to 1989, symbolizing the divide between communist and democratic Europe." },
      { q: "Which ancient civilization built the Great Wall?", options: ["Roman", "Chinese", "Egyptian", "Greek"], correct: 1,
        explanation: "The Great Wall of China was built over centuries by various Chinese dynasties to protect against invasions." },
      { q: "What year did Christopher Columbus first reach the Americas?", options: ["1392", "1492", "1592", "1692"], correct: 1,
        explanation: "Columbus's first voyage across the Atlantic reached the Americas in 1492." },
      { q: "Which country gifted the Statue of Liberty to the United States?", options: ["England", "France", "Spain", "Italy"], correct: 1,
        explanation: "France gave the Statue of Liberty to the U.S. in 1886 as a gift symbolizing friendship and liberty." },
      { q: "What was the name of the ship the Pilgrims sailed to America on?", options: ["Mayflower", "Santa Maria", "Endeavour", "Beagle"], correct: 0,
        explanation: "The Mayflower carried English Pilgrims to what is now Massachusetts in 1620." },
      { q: "Who was known as the 'Father of the Nation' in India?", options: ["Jawaharlal Nehru", "Mahatma Gandhi", "Indira Gandhi", "Subhas Chandra Bose"], correct: 1,
        explanation: "Mahatma Gandhi led India's independence movement through nonviolent resistance and is honored with that title." }
    ],
    [
      { q: "Who wrote the Declaration of Independence?", options: ["Thomas Jefferson", "Abraham Lincoln", "James Madison", "Alexander Hamilton"], correct: 0,
        explanation: "Thomas Jefferson drafted the Declaration in 1776, though the Continental Congress reviewed and edited it." },
      { q: "In what year did the Titanic sink?", options: ["1905", "1912", "1918", "1923"], correct: 1,
        explanation: "The RMS Titanic sank on April 15, 1912, after hitting an iceberg on its maiden voyage." },
      { q: "Which country was first to send a human into space?", options: ["USA", "Soviet Union", "China", "France"], correct: 1,
        explanation: "The Soviet Union sent Yuri Gagarin into orbit in 1961 — the first human in space." },
      { q: "The French Revolution began in what year?", options: ["1776", "1789", "1804", "1815"], correct: 1,
        explanation: "The French Revolution began in 1789, leading to the end of the monarchy and major political change in France." },
      { q: "Who was the leader of Nazi Germany during WWII?", options: ["Joseph Stalin", "Winston Churchill", "Adolf Hitler", "Benito Mussolini"], correct: 2,
        explanation: "Adolf Hitler led Nazi Germany from 1933 until his death in 1945." },
      { q: "What event triggered the start of World War I?", options: ["Assassination of Archduke Franz Ferdinand", "Attack on Pearl Harbor", "Sinking of the Lusitania", "The Treaty of Versailles"], correct: 0,
        explanation: "The 1914 assassination of Archduke Franz Ferdinand of Austria-Hungary set off the chain of events leading to WWI." },
      { q: "Which U.S. president issued the Emancipation Proclamation?", options: ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "Andrew Jackson"], correct: 1,
        explanation: "Lincoln issued the Emancipation Proclamation in 1863, declaring enslaved people in Confederate states to be free." },
      { q: "What was the name of the period of economic hardship in the 1930s?", options: ["The Gilded Age", "The Great Depression", "The Industrial Revolution", "The Progressive Era"], correct: 1,
        explanation: "The Great Depression was a severe worldwide economic downturn beginning in 1929 and lasting through much of the 1930s." },
      { q: "Which explorer led the first expedition to circumnavigate the globe?", options: ["Vasco da Gama", "Ferdinand Magellan", "Christopher Columbus", "James Cook"], correct: 1,
        explanation: "Magellan's expedition (1519–1522), though he died partway through, was the first to circumnavigate the Earth." },
      { q: "What was the Berlin Airlift a response to?", options: ["A famine in Germany", "A Soviet blockade of West Berlin", "A civil war in Germany", "An earthquake"], correct: 1,
        explanation: "In 1948–49, the Allies airlifted supplies into West Berlin after the Soviet Union blockaded ground access to the city." }
    ],
    [
      { q: "The Magna Carta, signed in 1215, primarily limited the power of whom?", options: ["The Pope", "The English king", "The French king", "Roman senators"], correct: 1,
        explanation: "The Magna Carta limited King John of England's power, establishing that even the king was subject to the law." },
      { q: "Which treaty formally ended World War I?", options: ["Treaty of Paris", "Treaty of Versailles", "Treaty of Rome", "Treaty of Vienna"], correct: 1,
        explanation: "The Treaty of Versailles, signed in 1919, formally ended World War I and imposed heavy penalties on Germany." },
      { q: "The Cold War was primarily a rivalry between which two powers?", options: ["USA and China", "USA and Soviet Union", "UK and Germany", "France and USSR"], correct: 1,
        explanation: "The Cold War (roughly 1947–1991) was a geopolitical rivalry between the United States and the Soviet Union." },
      { q: "What ancient civilization built Machu Picchu?", options: ["Aztec", "Maya", "Inca", "Olmec"], correct: 2,
        explanation: "Machu Picchu was built by the Inca civilization in the 15th century, in present-day Peru." },
      { q: "The Renaissance began in which country?", options: ["France", "England", "Italy", "Spain"], correct: 2,
        explanation: "The Renaissance began in Italy in the 14th century before spreading across Europe." },
      { q: "Which empire was ruled by Genghis Khan?", options: ["Ottoman Empire", "Mongol Empire", "Persian Empire", "Byzantine Empire"], correct: 1,
        explanation: "Genghis Khan founded and led the Mongol Empire, which became the largest contiguous land empire in history." },
      { q: "The Treaty of Tordesillas divided newly claimed lands between which two countries?", options: ["England and France", "Spain and Portugal", "Netherlands and England", "France and Portugal"], correct: 1,
        explanation: "The 1494 Treaty of Tordesillas divided lands outside Europe between Spain and Portugal along a meridian line." },
      { q: "What is generally considered the primary cause of the fall of the Western Roman Empire?", options: ["A single major battle", "A combination of invasions, economic troubles, and political instability", "A volcanic eruption", "A plague alone"], correct: 1,
        explanation: "Historians generally attribute Rome's fall to a combination of factors — barbarian invasions, economic decline, and political corruption — rather than one single cause." },
      { q: "The Opium Wars were fought between China and which country?", options: ["France", "Britain", "Russia", "Japan"], correct: 1,
        explanation: "The Opium Wars (1839–1860) were fought between Qing China and Britain over trade, including the opium trade." },
      { q: "Who was the first Emperor of unified China?", options: ["Confucius", "Qin Shi Huang", "Sun Tzu", "Kublai Khan"], correct: 1,
        explanation: "Qin Shi Huang unified China's warring states in 221 BCE and became its first emperor." }
    ]
  ],
  geography: [
    [
      { q: "What is the longest river in the world?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], correct: 1,
        explanation: "The Nile flows about 6,650 km through northeastern Africa, generally considered the longest river in the world." },
      { q: "Which country currently has the largest population?", options: ["USA", "India", "China", "Indonesia"], correct: 1,
        explanation: "India surpassed China to become the world's most populous country in 2023, according to United Nations estimates." },
      { q: "What is the smallest country in the world?", options: ["Monaco", "San Marino", "Vatican City", "Liechtenstein"], correct: 2,
        explanation: "Vatican City, an independent city-state in Rome, covers just about 0.44 square kilometers." },
      { q: "Which continent is the Sahara Desert located on?", options: ["Asia", "Africa", "South America", "Australia"], correct: 1,
        explanation: "The Sahara spans much of North Africa, covering roughly 9 million square kilometers." },
      { q: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correct: 2,
        explanation: "Ottawa, located in Ontario, has been Canada's capital since 1857, chosen partly for its position between English and French Canada." },
      { q: "Which country is known as the 'Land of the Rising Sun'?", options: ["China", "Japan", "Thailand", "South Korea"], correct: 1,
        explanation: "Japan is nicknamed the 'Land of the Rising Sun' because, from East Asia, the sun appears to rise from its direction." },
      { q: "What is the capital city of France?", options: ["Marseille", "Lyon", "Paris", "Nice"], correct: 2,
        explanation: "Paris has been the capital of France since the late 10th century." },
      { q: "Which continent is the largest by land area?", options: ["Africa", "Asia", "North America", "Europe"], correct: 1,
        explanation: "Asia is the largest continent, covering about 30% of Earth's total land area." },
      { q: "What ocean lies between Africa and Australia?", options: ["Atlantic", "Pacific", "Indian", "Arctic"], correct: 2,
        explanation: "The Indian Ocean lies between Africa, Asia, and Australia." },
      { q: "Which U.S. state is the largest by area?", options: ["Texas", "California", "Alaska", "Montana"], correct: 2,
        explanation: "Alaska is by far the largest U.S. state by land area, more than twice the size of Texas." }
    ],
    [
      { q: "Which mountain range separates Europe from Asia?", options: ["Alps", "Andes", "Ural Mountains", "Himalayas"], correct: 2,
        explanation: "The Ural Mountains run north-south through Russia and are traditionally treated as the boundary between Europe and Asia." },
      { q: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], correct: 3,
        explanation: "The Pacific Ocean is the largest and deepest ocean, covering about a third of Earth's surface." },
      { q: "Which desert is the largest hot desert in the world?", options: ["Gobi", "Sahara", "Kalahari", "Mojave"], correct: 1,
        explanation: "The Sahara is the largest hot desert in the world, covering much of North Africa." },
      { q: "What is the tallest mountain in the world (above sea level)?", options: ["K2", "Mount Kilimanjaro", "Mount Everest", "Denali"], correct: 2,
        explanation: "Mount Everest, in the Himalayas, stands at about 8,849 meters — the tallest mountain above sea level." },
      { q: "Which of these countries is transcontinental, spanning both Europe and Asia?", options: ["Egypt", "Turkey", "Brazil", "Japan"], correct: 1,
        explanation: "Turkey spans two continents — a small part (Eastern Thrace) lies in Europe, while the majority (Anatolia) lies in Asia." },
      { q: "Which river flows through Egypt and empties into the Mediterranean Sea?", options: ["Amazon", "Nile", "Congo", "Niger"], correct: 1,
        explanation: "The Nile flows north through Egypt and empties into the Mediterranean Sea." },
      { q: "What is the name of the imaginary line at 0° longitude?", options: ["Equator", "Prime Meridian", "Tropic of Cancer", "International Date Line"], correct: 1,
        explanation: "The Prime Meridian, passing through Greenwich, England, marks 0° longitude and divides the Eastern and Western Hemispheres." },
      { q: "Which country is home to most of the Amazon Rainforest?", options: ["Peru", "Colombia", "Brazil", "Venezuela"], correct: 2,
        explanation: "While the Amazon Rainforest spans several countries, the majority of it lies within Brazil." },
      { q: "What term describes a large, flat, treeless Arctic region?", options: ["Savanna", "Tundra", "Steppe", "Prairie"], correct: 1,
        explanation: "Tundra describes cold, treeless regions with permanently frozen subsoil, found in Arctic and high-altitude areas." },
      { q: "Which country consists of over 17,000 islands?", options: ["Philippines", "Indonesia", "Japan", "New Zealand"], correct: 1,
        explanation: "Indonesia is the world's largest archipelago, made up of more than 17,000 islands." }
    ],
    [
      { q: "Which country has the most time zones?", options: ["Russia", "USA", "France", "China"], correct: 2,
        explanation: "Thanks to its overseas territories, France spans 12 time zones — more than any other country." },
      { q: "What is the driest place on Earth (excluding polar regions)?", options: ["Sahara Desert", "Atacama Desert", "Death Valley", "Gobi Desert"], correct: 1,
        explanation: "The Atacama Desert in Chile is considered the driest non-polar desert on Earth, with some areas receiving almost no rainfall." },
      { q: "Which strait separates Europe and Africa at its narrowest point?", options: ["Strait of Hormuz", "Strait of Gibraltar", "Bering Strait", "Strait of Malacca"], correct: 1,
        explanation: "The Strait of Gibraltar separates Spain (Europe) from Morocco (Africa) at its narrowest point, about 13 km wide." },
      { q: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: 2,
        explanation: "Canberra — not Sydney or Melbourne — is Australia's capital, purpose-built as a compromise between the two rival cities." },
      { q: "Which landlocked country is entirely surrounded by South Africa?", options: ["Botswana", "Eswatini", "Lesotho", "Zimbabwe"], correct: 2,
        explanation: "Lesotho is a small landlocked country completely surrounded by South Africa — one of only three such 'enclave countries' in the world." },
      { q: "What is the world's largest coral reef system?", options: ["Belize Barrier Reef", "Great Barrier Reef", "Red Sea Coral Reef", "Florida Reef"], correct: 1,
        explanation: "The Great Barrier Reef, off the coast of Australia, is the world's largest coral reef system." },
      { q: "Which country is often considered the largest transcontinental country, spanning Europe and Asia?", options: ["Egypt", "Russia", "Kazakhstan", "Turkey"], correct: 1,
        explanation: "Russia spans both Europe and Asia and is by far the largest country in the world by land area." },
      { q: "What is the name of the supercontinent that existed roughly 300 million years ago?", options: ["Gondwana", "Laurasia", "Pangaea", "Rodinia"], correct: 2,
        explanation: "Pangaea was the supercontinent that existed roughly 335 to 175 million years ago before splitting into today's continents." },
      { q: "Which African country was never colonized by a European power?", options: ["Kenya", "Ethiopia", "Nigeria", "Ghana"], correct: 1,
        explanation: "Ethiopia successfully resisted European colonization, notably defeating Italy at the Battle of Adwa in 1896." },
      { q: "What is the term for a city that serves as the seat of a country's government?", options: ["Metropolis", "Capital", "Province", "Territory"], correct: 1,
        explanation: "A capital is the city designated as the seat of a country's government." }
    ]
  ],
  english: [
    [
      { q: "Which word is a synonym for 'happy'?", options: ["Joyful", "Sad", "Angry", "Tired"], correct: 0,
        explanation: "A synonym is a word with a similar meaning — 'joyful' means feeling or expressing happiness, just like 'happy.'" },
      { q: "What is the past tense of 'go'?", options: ["Goed", "Went", "Gone", "Going"], correct: 1,
        explanation: "'Go' is an irregular verb — its simple past tense is 'went.' 'Gone' is the past participle, used with helping verbs like 'have.'" },
      { q: "Which of these is a proper noun?", options: ["dog", "London", "quickly", "happiness"], correct: 1,
        explanation: "Proper nouns name specific people, places, or things and are capitalized — 'London' names a specific city." },
      { q: "What type of word describes a noun?", options: ["Verb", "Adjective", "Adverb", "Pronoun"], correct: 1,
        explanation: "Adjectives describe or modify nouns, telling us more about qualities like size, color, or feeling." },
      { q: "Who wrote 'Romeo and Juliet'?", options: ["Charles Dickens", "William Shakespeare", "Mark Twain", "Jane Austen"], correct: 1,
        explanation: "William Shakespeare wrote this tragedy around 1594–96; it remains one of his most performed plays." },
      { q: "Which word means the opposite of 'big'?", options: ["Large", "Small", "Tall", "Wide"], correct: 1,
        explanation: "'Small' is an antonym (opposite) of 'big,' both describing size." },
      { q: "What punctuation mark ends a question?", options: ["Period", "Comma", "Question mark", "Exclamation mark"], correct: 2,
        explanation: "A question mark (?) is used at the end of a sentence that asks something." },
      { q: "Which word is a pronoun?", options: ["Run", "She", "Quickly", "Happy"], correct: 1,
        explanation: "Pronouns replace nouns in a sentence — 'she' stands in for a person's name." },
      { q: "What is the plural of 'cat'?", options: ["Cat", "Cats", "Cates", "Caties"], correct: 1,
        explanation: "Most English nouns form their plural by simply adding -s, as in 'cat' becoming 'cats.'" },
      { q: "Which of these is a complete sentence?", options: ["Running fast.", "The dog barked.", "Under the table.", "Because it rained."], correct: 1,
        explanation: "A complete sentence needs a subject and a verb expressing a full thought — 'The dog barked' has both." }
    ],
    [
      { q: "What is a metaphor?", options: ["A comparison using 'like' or 'as'", "A direct comparison without using 'like' or 'as'", "A word that imitates a sound", "A repeated sound at the start of words"], correct: 1,
        explanation: "A metaphor directly states that one thing IS another, without using 'like' or 'as' — that's what separates it from a simile." },
      { q: "What is the plural of 'child'?", options: ["Childs", "Childes", "Children", "Childrens"], correct: 2,
        explanation: "'Child' has an irregular plural form, 'children,' rather than adding -s or -es." },
      { q: "Which sentence uses correct subject-verb agreement?", options: ["The dogs barks loudly.", "The dog bark loudly.", "The dogs bark loudly.", "The dog barking loudly."], correct: 2,
        explanation: "The plural subject 'dogs' takes the plural verb form 'bark' (without -s), matching in number." },
      { q: "What is a synonym for 'enormous'?", options: ["Tiny", "Huge", "Quiet", "Fast"], correct: 1,
        explanation: "'Huge' means very large, matching the meaning of 'enormous.'" },
      { q: "Identify the adverb in this sentence: 'She sang beautifully.'", options: ["She", "sang", "beautifully", "There is no adverb"], correct: 2,
        explanation: "'Beautifully' modifies the verb 'sang,' describing how she sang — that's the role of an adverb." },
      { q: "What is the term for a word that sounds like another but differs in spelling and meaning?", options: ["Synonym", "Antonym", "Homophone", "Acronym"], correct: 2,
        explanation: "Homophones sound alike but differ in spelling and meaning, like 'their' and 'there.'" },
      { q: "Which sentence uses a simile?", options: ["He is as brave as a lion.", "He is a lion.", "The lion roared loudly.", "Lions live in prides."], correct: 0,
        explanation: "A simile compares two things using 'like' or 'as' — here comparing bravery to a lion using 'as...as.'" },
      { q: "Which is the correct spelling?", options: ["Recieve", "Receive", "Both are correct", "Neither is correct"], correct: 1,
        explanation: "The rule 'i before e except after c' applies here — since it follows 'c,' it's spelled 'receive.'" },
      { q: "What part of speech is the word 'quickly'?", options: ["Noun", "Verb", "Adjective", "Adverb"], correct: 3,
        explanation: "Words ending in -ly that modify verbs, like 'quickly,' are typically adverbs, describing how an action is done." },
      { q: "Which of these is an example of alliteration?", options: ["The big striped balloon floated away.", "The cat sat on the mat.", "She sells seashells.", "Time flies when you're having fun."], correct: 2,
        explanation: "Alliteration is the repetition of initial consonant sounds in nearby words, as in 'she sells seashells' repeating the 's' sound." }
    ],
    [
      { q: "What literary device is used in 'The wind whispered through the trees'?", options: ["Simile", "Personification", "Alliteration", "Hyperbole"], correct: 1,
        explanation: "Personification gives human qualities — like whispering — to non-human things, here the wind." },
      { q: "Which of these is an example of (situational) irony?", options: ["A fire station burns down.", "A dog barks at night.", "Rain falls during a storm.", "A student studies for a test."], correct: 0,
        explanation: "It's ironic because a fire station, meant to prevent fires, burning down directly contradicts what you'd expect." },
      { q: "What is the correct past participle of 'to write'?", options: ["Writed", "Wrote", "Written", "Writing"], correct: 2,
        explanation: "'Write' is irregular: present 'write,' simple past 'wrote,' past participle 'written' (used with has/have/had)." },
      { q: "Which sentence is in the passive voice?", options: ["The chef cooked the meal.", "The meal was cooked by the chef.", "The chef is cooking the meal.", "The chef will cook the meal."], correct: 1,
        explanation: "In passive voice, the subject receives the action rather than performing it — here 'the meal' receives the action of being cooked." },
      { q: "What does the prefix 'un-' typically mean?", options: ["Again", "Not or opposite of", "Before", "After"], correct: 1,
        explanation: "The prefix 'un-' generally reverses or negates the root word's meaning, as in 'unhappy' (not happy)." },
      { q: "What is an oxymoron, as in the example 'jumbo shrimp'?", options: ["A word with two meanings", "A combination of contradictory terms", "A very long word", "A word borrowed from another language"], correct: 1,
        explanation: "An oxymoron combines two contradictory or opposite terms for effect, like 'jumbo shrimp' or 'deafening silence.'" },
      { q: "Which sentence contains a dangling modifier?", options: ["Walking down the street, the trees looked beautiful.", "She walked down the street and admired the trees.", "The trees were beautiful as she walked down the street.", "While walking, she admired the trees."], correct: 0,
        explanation: "The first sentence incorrectly implies the trees were walking, since the modifying phrase isn't clearly attached to the person doing the walking." },
      { q: "What is the term for the perspective from which a story is told?", options: ["Tone", "Point of view", "Setting", "Theme"], correct: 1,
        explanation: "Point of view refers to who is telling the story — first person, third person, and so on." },
      { q: "Which of these is a compound-complex sentence?", options: ["She ran.", "She ran because she was late.", "She ran, and he walked.", "She ran because she was late, and he walked slowly."], correct: 3,
        explanation: "A compound-complex sentence contains at least two independent clauses ('she ran...' and 'he walked slowly') plus at least one dependent clause ('because she was late')." },
      { q: "What does 'onomatopoeia' refer to?", options: ["Words that imitate sounds", "Repeated consonant sounds", "A comparison using 'like' or 'as'", "A word with multiple meanings"], correct: 0,
        explanation: "Onomatopoeia describes words that phonetically imitate the sound they describe, like 'buzz' or 'clang.'" }
    ]
  ],
  "computer-science": [
    [
      { q: "What does CPU stand for?", options: ["Central Process Unit", "Central Processing Unit", "Computer Personal Unit", "Central Processor Utility"], correct: 1,
        explanation: "The CPU is often called the computer's 'brain' — it carries out instructions from programs through calculations and logic operations." },
      { q: "Which of these is a programming language?", options: ["HTML", "Python", "HTTP", "USB"], correct: 1,
        explanation: "Python is a general-purpose programming language. HTML is a markup language, and HTTP/USB are protocols and standards, not languages." },
      { q: "What does 'bug' mean in coding?", options: ["A useful feature", "An error in code", "A type of variable", "A security certificate"], correct: 1,
        explanation: "The term dates back to early computing — a literal moth caused a malfunction in an early computer in 1947, and the name stuck." },
      { q: "What two digits does binary code use?", options: ["0 and 1", "A and B", "1 and 2", "X and Y"], correct: 0,
        explanation: "Computers store and process information using binary — just two digits, 0 and 1, representing off/on electrical states." },
      { q: "What does 'www' stand for?", options: ["World Wide Web", "World Wide Wire", "Web Wide World", "Wide World Web"], correct: 0,
        explanation: "The World Wide Web, invented by Tim Berners-Lee in 1989, is the system of linked pages accessed over the internet." },
      { q: "What does 'GUI' stand for?", options: ["General User Input", "Graphical User Interface", "Global Utility Index", "Guided User Instructions"], correct: 1,
        explanation: "A GUI (Graphical User Interface) lets users interact with a computer through visual elements like windows, icons, and buttons, instead of text commands." },
      { q: "Which of these is an example of computer hardware?", options: ["Operating system", "Keyboard", "Web browser", "Antivirus software"], correct: 1,
        explanation: "Hardware refers to physical components of a computer, like a keyboard, monitor, or hard drive — unlike software, which is code." },
      { q: "What does 'save' typically do in most software?", options: ["Deletes a file", "Stores your current work to a file", "Prints a document", "Closes the program"], correct: 1,
        explanation: "Saving writes your current work to storage (like a hard drive) so it isn't lost when the program closes." },
      { q: "What is the term for unwanted software designed to harm a computer?", options: ["Firmware", "Malware", "Freeware", "Shareware"], correct: 1,
        explanation: "Malware is malicious software designed to damage, disrupt, or gain unauthorized access to computer systems." },
      { q: "What does Wi-Fi allow devices to do?", options: ["Charge wirelessly", "Connect to a network without cables", "Print documents", "Store extra files"], correct: 1,
        explanation: "Wi-Fi is a wireless networking technology that lets devices connect to the internet or a local network without physical cables." }
    ],
    [
      { q: "What is an algorithm?", options: ["A type of computer", "A set of steps to solve a problem", "A programming language", "A type of virus"], correct: 1,
        explanation: "An algorithm is a precise, step-by-step procedure or set of rules designed to solve a problem or complete a task." },
      { q: "What does RAM stand for?", options: ["Random Access Memory", "Read Access Memory", "Rapid Access Memory", "Random Allocation Memory"], correct: 0,
        explanation: "RAM (Random Access Memory) is temporary memory a computer uses to store data it's actively working with." },
      { q: "What symbol commonly starts a comment in Python?", options: ["//", "#", "<!--", "/*"], correct: 1,
        explanation: "In Python, the '#' symbol marks the rest of a line as a comment, which is ignored when the code runs." },
      { q: "What does 'IDE' stand for in programming?", options: ["Integrated Development Environment", "Internal Data Exchange", "Interface Design Element", "Instructional Data Engine"], correct: 0,
        explanation: "An IDE is software that bundles tools like a code editor, debugger, and compiler to make programming easier." },
      { q: "What data structure works on a 'First In, First Out' basis?", options: ["Stack", "Queue", "Array", "Tree"], correct: 1,
        explanation: "A queue processes items in the order they arrive — first in, first out — like a line of people waiting." },
      { q: "What does 'debugging' mean?", options: ["Writing new code", "Finding and fixing errors in code", "Deleting a program", "Compiling code"], correct: 1,
        explanation: "Debugging is the process of finding and correcting errors ('bugs') in a program's code." },
      { q: "What is a 'variable' in programming?", options: ["A fixed value that never changes", "A named storage location for data that can change", "A type of loop", "A programming language"], correct: 1,
        explanation: "A variable is a named container used to store data that can be changed while a program runs." },
      { q: "What does 'HTML' stand for?", options: ["HyperText Markup Language", "High Tech Modern Language", "Hyperlink and Text Markup Language", "Home Tool Markup Language"], correct: 0,
        explanation: "HTML (HyperText Markup Language) is the standard language used to structure content on web pages." },
      { q: "What is the purpose of a 'for loop' in programming?", options: ["To store data", "To repeat a block of code a set number of times", "To define a function", "To connect to the internet"], correct: 1,
        explanation: "A for loop lets a program repeat a set of instructions a specific number of times without rewriting the code." },
      { q: "What does 'CSS' control on a webpage?", options: ["The page's logic and behavior", "The page's visual styling and layout", "The page's database", "The page's server location"], correct: 1,
        explanation: "CSS (Cascading Style Sheets) controls how a webpage looks — colors, fonts, layout — separate from its content (HTML) or behavior (JavaScript)." }
    ],
    [
      { q: "What is the time complexity of binary search on a sorted array?", options: ["O(1)", "O(n)", "O(log n)", "O(n²)"], correct: 2,
        explanation: "Binary search repeatedly halves the search space, giving it logarithmic time complexity, O(log n)." },
      { q: "What does 'recursion' mean in programming?", options: ["A loop that never ends", "A function that calls itself", "A type of variable", "A way to sort data"], correct: 1,
        explanation: "Recursion is when a function calls itself to solve smaller instances of the same problem, typically with a base case to stop." },
      { q: "What does SQL primarily do?", options: ["Manage and query relational databases", "Test software quality", "Store and sort arrays", "Handle network protocols"], correct: 0,
        explanation: "SQL (Structured Query Language) is used to create, read, update, and manage data in relational databases." },
      { q: "What is the main difference between a stack and a queue?", options: ["Stacks are FIFO, queues are LIFO", "Stacks are LIFO, queues are FIFO", "They are the same thing", "Stacks only store numbers"], correct: 1,
        explanation: "A stack is Last In, First Out (like a stack of plates), while a queue is First In, First Out (like a line)." },
      { q: "What does 'API' stand for?", options: ["Application Programming Interface", "Automated Program Instruction", "Applied Programming Index", "Active Protocol Interface"], correct: 0,
        explanation: "An API (Application Programming Interface) defines how different software components communicate with each other." },
      { q: "What is 'Big O notation' used to describe?", options: ["The size of a hard drive", "How an algorithm's runtime or space grows with input size", "The number of bugs in a program", "The version of a programming language"], correct: 1,
        explanation: "Big O notation describes how an algorithm's time or space requirements scale as the input size grows, used to compare efficiency." },
      { q: "What does 'object-oriented programming' organize code around?", options: ["Functions only", "Objects that combine data and behavior", "Random values", "Hardware instructions"], correct: 1,
        explanation: "Object-oriented programming (OOP) structures code around 'objects' that bundle related data (properties) and behavior (methods) together." },
      { q: "What is a 'hash table' primarily used for?", options: ["Storing images", "Fast data lookup using key-value pairs", "Rendering graphics", "Managing network connections"], correct: 1,
        explanation: "A hash table stores data as key-value pairs and uses a hash function to enable very fast lookups, insertions, and deletions." },
      { q: "What does 'encryption' do to data?", options: ["Deletes it permanently", "Converts it into a coded form to protect it", "Compresses it to save space", "Duplicates it for backup"], correct: 1,
        explanation: "Encryption transforms readable data into a coded format that can only be read again with the correct decryption key, protecting it from unauthorized access." },
      { q: "What is the main advantage of a 'linked list' over an array?", options: ["Faster random access", "Easier resizing and insertion/removal", "Always uses less memory", "Can only store numbers"], correct: 1,
        explanation: "Linked lists can grow or shrink easily and allow efficient insertion/removal at any point, unlike arrays, which have fixed sizes and costly middle insertions." }
    ]
  ],
  economics: [
    [
      { q: "What does 'supply and demand' describe?", options: ["Government spending", "The relationship between price and availability of goods", "Bank interest rates", "Stock market trends"], correct: 1,
        explanation: "Supply and demand describes how the availability of a good and how much people want it interact to determine its market price." },
      { q: "What is inflation?", options: ["A rise in the general price level over time", "A decrease in prices", "A type of tax", "A trade agreement"], correct: 0,
        explanation: "Inflation is measured as the percentage increase in the general price level of goods and services over time, which reduces purchasing power." },
      { q: "What does GDP stand for?", options: ["Gross Domestic Product", "General Domestic Price", "Global Development Plan", "Gross Development Percentage"], correct: 0,
        explanation: "GDP measures the total monetary value of all goods and services produced within a country over a given period." },
      { q: "What is a 'market economy'?", options: ["Government controls all production", "Prices are set by supply and demand", "No trade is allowed", "Prices are fixed by law"], correct: 1,
        explanation: "In a market economy, prices aren't set by the government — they emerge from the interaction of buyers and sellers." },
      { q: "What is opportunity cost?", options: ["The cost of borrowing money", "The value of the next best alternative given up", "The tax on goods", "The interest earned on savings"], correct: 1,
        explanation: "Opportunity cost is the value of the best alternative you give up when you make a choice — a core idea behind every trade-off." },
      { q: "What is money primarily used for in an economy?", options: ["Only for saving", "A medium of exchange for goods and services", "Only for taxes", "A type of resource"], correct: 1,
        explanation: "Money serves as a medium of exchange, making it easier to trade goods and services compared to bartering." },
      { q: "What does 'export' mean in trade?", options: ["Buying goods from another country", "Selling goods to another country", "Storing goods domestically", "Destroying unsold goods"], correct: 1,
        explanation: "Exporting means selling goods or services produced in one country to buyers in another country." },
      { q: "What is a 'budget'?", options: ["A type of tax", "A plan for how to spend and save money", "A bank account", "A type of loan"], correct: 1,
        explanation: "A budget is a plan that outlines expected income and expenses over a period of time." },
      { q: "What does 'interest rate' refer to when borrowing money?", options: ["The total amount borrowed", "The cost of borrowing money, expressed as a percentage", "A type of tax on income", "The value of a currency"], correct: 1,
        explanation: "An interest rate is the percentage charged by a lender for the use of borrowed money, on top of the amount borrowed." },
      { q: "What is a 'consumer'?", options: ["A person who produces goods", "A person or business that buys goods and services", "A government agency", "A bank"], correct: 1,
        explanation: "A consumer is an individual or entity that purchases goods and services for personal use." }
    ],
    [
      { q: "What does 'scarcity' mean in economics?", options: ["Unlimited resources", "Limited resources relative to unlimited wants", "A type of currency", "A government policy"], correct: 1,
        explanation: "Scarcity is the basic economic problem: resources are limited while human wants are essentially unlimited, forcing choices about allocation." },
      { q: "What is a 'monopoly'?", options: ["Many companies competing freely", "A single seller dominating a market", "A government-owned bank", "A type of currency"], correct: 1,
        explanation: "A monopoly exists when a single company or seller dominates a market with no significant competition." },
      { q: "What does 'fiscal policy' refer to?", options: ["A central bank's control of interest rates", "Government use of spending and taxation to influence the economy", "Company hiring practices", "International trade agreements"], correct: 1,
        explanation: "Fiscal policy is how governments use spending and taxation to influence economic conditions — distinct from monetary policy." },
      { q: "What is a 'trade deficit'?", options: ["Exporting more than importing", "Importing more than exporting", "Having no international trade", "Equal imports and exports"], correct: 1,
        explanation: "A trade deficit occurs when a country imports more goods and services than it exports." },
      { q: "What does the 'unemployment rate' measure?", options: ["Total population without jobs", "The share of the labor force actively seeking but not finding work", "Total number of retired people", "Average income per person"], correct: 1,
        explanation: "The unemployment rate specifically measures the share of people in the labor force who are jobless and actively seeking work — not the whole population." },
      { q: "What is 'competition' in a market economy?", options: ["When one company controls everything", "Multiple sellers vying for customers, often improving quality and lowering prices", "A government-set rule", "A type of tax"], correct: 1,
        explanation: "Competition occurs when multiple businesses compete for customers, which can drive innovation, better quality, and lower prices." },
      { q: "What does a 'demand curve' typically show?", options: ["The relationship between price and quantity demanded", "The total cost of production", "Government spending over time", "The population of a country"], correct: 0,
        explanation: "A demand curve graphs how the quantity of a good demanded changes as its price changes, usually showing an inverse relationship." },
      { q: "What is a 'subsidy'?", options: ["A tax on imports", "Financial assistance from the government to support a business or activity", "A type of bank loan", "A fee charged by a company"], correct: 1,
        explanation: "A subsidy is financial support given by a government to encourage or support a particular industry, activity, or group." },
      { q: "What does 'purchasing power' refer to?", options: ["The amount of money a country prints", "The quantity of goods and services money can buy", "A type of stock", "A bank's total assets"], correct: 1,
        explanation: "Purchasing power describes how much a given amount of money can actually buy, which decreases as prices rise (inflation)." },
      { q: "What is a 'recession'?", options: ["A period of significant economic growth", "A significant decline in economic activity lasting more than a few months", "A type of tax cut", "A stock market holiday"], correct: 1,
        explanation: "A recession is a period of significant, widespread decline in economic activity, typically measured by falling GDP over two consecutive quarters." }
    ],
    [
      { q: "What is 'monetary policy' typically controlled by?", options: ["The elected government directly", "A country's central bank", "Private corporations", "Labor unions"], correct: 1,
        explanation: "Monetary policy — controlling interest rates and money supply — is typically managed by a country's central bank." },
      { q: "What does 'comparative advantage' explain in trade?", options: ["Why countries should be self-sufficient", "Why countries benefit from specializing in what they produce relatively efficiently", "Why tariffs are always beneficial", "Why exchange rates never change"], correct: 1,
        explanation: "Comparative advantage explains why countries gain from trade by specializing in goods they can produce relatively more efficiently, even if another country could produce everything more efficiently overall." },
      { q: "What is 'stagflation'?", options: ["High growth and low inflation", "Stagnant growth combined with high inflation", "Falling prices during a recession", "Rapid growth with no inflation"], correct: 1,
        explanation: "Stagflation is the unusual and difficult combination of slow economic growth, high unemployment, and high inflation happening at once." },
      { q: "What does a country's central bank primarily do?", options: ["Collect income tax", "Manage the money supply and set interest rates", "Regulate private hiring", "Run the stock exchange"], correct: 1,
        explanation: "A central bank manages a country's money supply and key interest rates, aiming for stable prices and steady growth." },
      { q: "What is the 'law of diminishing returns'?", options: ["Producing more always increases profit", "Adding more of one input eventually yields smaller output gains", "Prices always fall over time", "Supply always equals demand"], correct: 1,
        explanation: "The law of diminishing returns states that adding more units of one input, while others stay fixed, eventually produces smaller and smaller additional output." },
      { q: "What does 'elasticity of demand' measure?", options: ["How much a product weighs", "How responsive quantity demanded is to a change in price", "The total supply of a good", "The interest rate on loans"], correct: 1,
        explanation: "Elasticity of demand measures how much the quantity demanded of a good changes in response to a change in its price." },
      { q: "What is a 'progressive tax system'?", options: ["Everyone pays the same tax rate", "Tax rates increase as income increases", "Only businesses pay taxes", "Tax rates decrease as income increases"], correct: 1,
        explanation: "In a progressive tax system, people with higher incomes pay a higher percentage of their income in taxes than those with lower incomes." },
      { q: "What does 'quantitative easing' involve?", options: ["A central bank cutting government spending", "A central bank buying assets to increase money supply and stimulate the economy", "Raising interest rates sharply", "Reducing taxes for businesses only"], correct: 1,
        explanation: "Quantitative easing is when a central bank buys financial assets to inject money into the economy and encourage lending and spending, often used when interest rates are already very low." },
      { q: "What does 'GDP per capita' measure?", options: ["Total national debt", "Average economic output per person in a country", "Total government spending", "Total exports minus imports"], correct: 1,
        explanation: "GDP per capita divides a country's total GDP by its population, giving a rough measure of average economic output or living standards per person." },
      { q: "What is the difference between microeconomics and macroeconomics?", options: ["There is no difference", "Microeconomics studies individual markets and decisions; macroeconomics studies the economy as a whole", "Macroeconomics only studies small businesses", "Microeconomics only studies government policy"], correct: 1,
        explanation: "Microeconomics focuses on individual consumers, firms, and markets, while macroeconomics studies economy-wide phenomena like inflation, unemployment, and overall growth." }
    ]
  ]
};

// Returns 5 shuffled questions. Pass a chapterIndex (0, 1, or 2) to
// get that chapter specifically (used by Quests). Omit it to get a
// mixed pool across all chapters for that subject (used by Boss
// Fight, Duels, and the AI Tutor, where difficulty tiers don't apply).
function getQuestions(subjectId, chapterIndex) {
  const chapters = QUESTION_BANK[subjectId] || [];
  const pool = (typeof chapterIndex === "number")
    ? (chapters[chapterIndex] || [])
    : chapters.flat();
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, 5);
}
