// ------------------------------------------------------------------
// Brain Quest — AI Tutor, now a real chat interface.
//
// Type what you're stuck on ("I don't understand fractions") and the
// AI (Gemini, via functions/index.js's chatWithTutor) explains it
// conversationally. After any reply, you can ask for a tailored
// practice question, generated by Gemini specifically for what you
// were just talking about, then answered using the same quiz engine
// as everywhere else in the app.
//
// Free tier: 3 AI interactions per day (a chat message OR a practice
// question request each count as one use). Pro: unlimited, matching
// the existing Pro perk structure.
//
// Chat history is kept in memory only for this session — it resets
// on reload. That's a deliberate scope choice, not an oversight; see
// the README for what persisting it would take.
// ------------------------------------------------------------------

const FREE_DAILY_AI_LIMIT = 3;
const MIN_ATTEMPTS_FOR_WEAK_AREA = 3;

// Records a correct/incorrect answer against a subject's running
// stats, regardless of which mode (quest, boss, duel, tutor) it came
// from — this is what lets the tutor find your real weak areas.
async function recordSubjectStat(subjectId, isCorrect) {
  if (!currentUserData || !subjectId) return;
  if (!currentUserData.subjectStats) currentUserData.subjectStats = {};
  if (!currentUserData.subjectStats[subjectId]) {
    currentUserData.subjectStats[subjectId] = { correct: 0, wrong: 0 };
  }
  const key = isCorrect ? "correct" : "wrong";
  currentUserData.subjectStats[subjectId][key]++;

  if (currentUser) {
    await db.collection("users").doc(currentUser.uid).update({
      [`subjectStats.${subjectId}.${key}`]: firebase.firestore.FieldValue.increment(1)
    });
  }
}

// Finds the subject with the highest wrong-answer ratio, requiring a
// minimum number of attempts so a single unlucky guess doesn't get
// flagged as a "weakness." Returns null if there isn't enough data yet.
function getWeakestSubject() {
  const stats = (currentUserData && currentUserData.subjectStats) || {};
  let weakest = null;
  let weakestRatio = -1;

  SUBJECTS.forEach(s => {
    const st = stats[s.id];
    if (!st) return;
    const attempts = st.correct + st.wrong;
    if (attempts < MIN_ATTEMPTS_FOR_WEAK_AREA) return;
    const wrongRatio = st.wrong / attempts;
    if (wrongRatio > weakestRatio) {
      weakestRatio = wrongRatio;
      weakest = s;
    }
  });

  return weakest;
}

function ensureAiTutorIsForToday() {
  const today = new Date().toISOString().slice(0, 10);
  if (currentUserData.aiTutorDate !== today) {
    currentUserData.aiTutorDate = today;
    currentUserData.aiTutorUsesToday = 0;
  }
}

let _tutorChatHistory = []; // [{ role: "user"|"tutor", text: "..." }], in-memory only

function renderTutorScreen() {
  ensureAiTutorIsForToday();
  const isPro = currentUserData.isPro;
  const remaining = FREE_DAILY_AI_LIMIT - (currentUserData.aiTutorUsesToday || 0);

  document.getElementById("tutor-usage-note").textContent = isPro
    ? "⭐ Pro Tutor — unlimited messages and practice questions."
    : `Free Tutor — ${Math.max(remaining, 0)} of ${FREE_DAILY_AI_LIMIT} interactions left today.`;

  renderChatMessages();

  const atLimit = !isPro && remaining <= 0;
  document.getElementById("chat-input").disabled = atLimit;
  document.getElementById("chat-send-btn").disabled = atLimit;
  document.getElementById("chat-input").placeholder = atLimit
    ? "Come back tomorrow for more free messages"
    : "e.g. I don't understand fractions";
}

function renderChatMessages() {
  const container = document.getElementById("chat-messages");
  if (_tutorChatHistory.length === 0) {
    container.innerHTML = `<p class="chat-empty-state">Ask about anything you're stuck on to get started.</p>`;
    return;
  }
  container.innerHTML = _tutorChatHistory.map((msg, i) => `
    <div class="chat-bubble chat-bubble-${msg.role}">
      <p>${escapeHtml(msg.text)}</p>
      ${msg.role === "tutor" ? `<button class="btn btn-ghost chat-practice-btn" data-msg-index="${i}">Give me a practice question on this</button>` : ""}
    </div>
  `).join("");
  container.scrollTop = container.scrollHeight;

  container.querySelectorAll(".chat-practice-btn").forEach(btn => {
    btn.addEventListener("click", () => requestPracticeQuestion(Number(btn.dataset.msgIndex)));
  });
}

function useOneAiInteraction() {
  if (currentUserData.isPro) return true;
  ensureAiTutorIsForToday();
  const remaining = FREE_DAILY_AI_LIMIT - (currentUserData.aiTutorUsesToday || 0);
  if (remaining <= 0) return false;
  currentUserData.aiTutorUsesToday = (currentUserData.aiTutorUsesToday || 0) + 1;
  if (currentUser) {
    db.collection("users").doc(currentUser.uid).update({
      aiTutorDate: currentUserData.aiTutorDate,
      aiTutorUsesToday: currentUserData.aiTutorUsesToday
    });
  }
  return true;
}

document.getElementById("chat-input-form").addEventListener("submit", async (e) => {
  e.preventDefault();
  const input = document.getElementById("chat-input");
  const text = input.value.trim();
  if (!text) return;

  if (!useOneAiInteraction()) {
    renderTutorScreen();
    return;
  }

  _tutorChatHistory.push({ role: "user", text });
  input.value = "";
  renderChatMessages();

  document.getElementById("chat-send-btn").disabled = true;
  _tutorChatHistory.push({ role: "tutor", text: "Thinking..." });
  renderChatMessages();

  const weakest = getWeakestSubject();
  const reply = await fetchTutorChatReply({
    history: _tutorChatHistory.slice(0, -1),
    gradeLevel: currentUserData.gradeLevel,
    weakestSubject: weakest ? weakest.name : null
  });

  _tutorChatHistory[_tutorChatHistory.length - 1] = {
    role: "tutor",
    text: reply || "Sorry, I couldn't reach the tutor just now — please try again in a moment."
  };
  document.getElementById("chat-send-btn").disabled = false;
  renderTutorScreen();
});

async function requestPracticeQuestion(afterMsgIndex) {
  if (!useOneAiInteraction()) {
    renderTutorScreen();
    return;
  }

  const context = _tutorChatHistory.slice(0, afterMsgIndex + 1).map(m => `${m.role}: ${m.text}`).join("\n");
  const question = await fetchGeneratedPracticeQuestion({
    conversationContext: context,
    gradeLevel: currentUserData.gradeLevel
  });

  if (!question) {
    _tutorChatHistory.push({ role: "tutor", text: "Sorry, I couldn't generate a question just now — please try again." });
    renderTutorScreen();
    return;
  }

  currentQuiz = {
    mode: "tutor",
    subjectId: null,
    subjectName: "AI Tutor — Practice Question",
    questions: [question],
    index: 0,
    correctCount: 0
  };

  showScreen("quiz-section");
  document.getElementById("hearts-hud").classList.add("hidden");
  renderQuestion();
}

async function finishTutorSession() {
  const { correctCount, questions } = currentQuiz;
  const xpGained = currentQuiz.xpEarned || 0;
  await addXp(xpGained);

  document.getElementById("results-eyebrow").textContent = "Tutor practice question";
  document.getElementById("results-score").textContent = `${correctCount} / ${questions.length}`;
  document.getElementById("results-xp-gain").textContent = `+${xpGained} XP`;
  document.getElementById("results-upsell").classList.add("hidden");
  document.getElementById("results-message").textContent = correctCount === questions.length
    ? "Nice — you've got this one down."
    : "That's alright — ask the tutor to explain it again if you want another pass.";

  showScreen("results-section");
}
